const statusCodeParaTexto = statusCode => {
    const statusCodes = {
        '-1': { ok: 'log', msg: 'Erro interno, consulte o painel de desenvolvedor' }, 
        0: { ok: null, msg: '' }, 

        100: { ok: 'log', msg: 'Continuar 🚀' },
        101: { ok: 'log', msg: 'Mudando Protocolos 🚀' },
        102: { ok: 'log', msg: 'Processamento 🚀' },
        103: { ok: 'log', msg: 'Dicas Antecipadas 🚀' },

        200: { ok: 'ok', msg: 'OK 😃' },
        201: { ok: 'ok', msg: 'Criado 🎉' },
        202: { ok: 'ok', msg: 'Aceito 😊' },
        203: { ok: 'ok', msg: 'Informações Não Autoritativas 😊' },
        204: { ok: 'ok', msg: 'Sem Conteúdo 😐' },
        205: { ok: 'ok', msg: 'Redefinir Conteúdo 😐' },
        206: { ok: 'ok', msg: 'Conteúdo Parcial 😊' },
        207: { ok: 'ok', msg: 'Status Multi 😊' },
        208: { ok: 'ok', msg: 'Já Reportado 🎉' },
        226: { ok: 'ok', msg: 'IM Usado 🎉' },

        300: { ok: 'ok', msg: 'Múltipla Escolha 🧐' },
        301: { ok: 'ok', msg: 'Movido Permanentemente 🏠' },
        302: { ok: 'ok', msg: 'Encontrado 😃' },
        303: { ok: 'ok', msg: 'Ver Outros 😊' },
        304: { ok: 'ok', msg: 'Não Modificado 😐' },
        305: { ok: 'ok', msg: 'Use Proxy 🧐' },
        306: { ok: 'ok', msg: 'Proxy Switch 🧐' },
        307: { ok: 'ok', msg: 'Redirecionamento Temporário 😊' },
        308: { ok: 'ok', msg: 'Redirecionamento Permanente 🏠' },

        400: { ok: 'warning', msg: 'Requisição Inválida 😕' },
        401: { ok: 'warning', msg: 'Não Autorizado 😢' },
        402: { ok: 'warning', msg: 'Pagamento Necessário 💸' },
        403: { ok: 'warning', msg: 'Proibido 😡' },
        404: { ok: 'error', msg: 'Não Encontrado 😢' },
        405: { ok: 'warning', msg: 'Método não Permitido 🧐' },
        406: { ok: 'warning', msg: 'Não Aceitável ⛔' },
        407: { ok: 'warning', msg: 'Autenticação de Proxy Necessária 😢' },
        408: { ok: 'warning', msg: 'Tempo de Requisição Esgotou 😕' },
        409: { ok: 'warning', msg: 'Conflito 😡' },
        410: { ok: 'warning', msg: 'Desaparecido 😢' },
        411: { ok: 'warning', msg: 'Comprimento Necessário 😐' },
        412: { ok: 'warning', msg: 'Pré-condição Falhada 😕' },
        413: { ok: 'warning', msg: 'Entidade de Solicitação Muito Grande 😕' },
        414: { ok: 'warning', msg: 'URI de Solicitação Muito Longa 😕' },
        415: { ok: 'warning', msg: 'Tipo de Mídia Não Suportado 😕' },
        416: { ok: 'warning', msg: 'Faixa Não Satisfatória 😕' },
        417: { ok: 'warning', msg: 'Expectativa Falhada 😕' },
        418: { ok: 'warning', msg: 'Eu sou um bule de chá ☕' },
        421: { ok: 'warning', msg: 'Destino Não Encontrado 😢' },
        422: { ok: 'warning', msg: 'Entidade Improcessável 😕' },
        423: { ok: 'warning', msg: 'Fechado 😐' },
        424: { ok: 'warning', msg: 'Falha de Dependência 😕' },
        425: { ok: 'warning', msg: 'Coleção Não Ordenada 😐' },
        426: { ok: 'warning', msg: 'Upgrade Necessário 😐' },
        428: { ok: 'warning', msg: 'Pré-requisito Requerido 😕' },
        429: { ok: 'warning', msg: 'Muitas Solicitações 😡' },
        431: { ok: 'warning', msg: 'Campos de Cabeçalho de Solicitação Muito Grandes 😕' },
        451: { ok: 'warning', msg: 'Indisponível por Motivos Legais 😡' },

        500: { ok: 'error', msg: 'Erro Interno do Servidor 😣' },
        501: { ok: 'error', msg: 'Não Implementado 🤔' },
        502: { ok: 'error', msg: 'Bad Gateway 😣' },
        503: { ok: 'error', msg: 'Serviço Indisponível 😣' },
        504: { ok: 'error', msg: 'Gateway Timeout 😣' },
        505: { ok: 'error', msg: 'Versão do HTTP Não Suportada 🤔' },
        506: { ok: 'error', msg: 'Variação Também Negocia 🤔' },
        507: { ok: 'error', msg: 'Armazenamento Insuficiente 😣' },
        508: { ok: 'error', msg: 'Loop Detectado 😣' },
        510: { ok: 'error', msg: 'Não Estendido 🤔' },
        511: { ok: 'error', msg: 'Autenticação de Rede Requerida 😢' }
    };

    return statusCodes[statusCode] || { ok: 'log' , msg: `Código de status não reconhecido 🤔` };
}